### PR TITLE
Add compatibility with gitlab (and maybe others)

### PR DESCRIPTION
**Pull request by jorgifumi**
With this modification device_grid works with gitlab, before it crashes with message: undefined method `github'

### CODE REVIEW

**Comment by jorgifumi** [comment]
Signed!

**Review by KrauseFx — APPROVED** [review]
Nice, thanks. Are you using the device grid plugin successfully?

**Comment by jorgifumi** [comment]
> Nice, thanks. Are you using the device grid plugin successfully?

Yes, It's very useful! But I need this fix to work properly with Gitlab. Thanks for your amazing tools Felix!

**Comment by KrauseFx** [comment]
I don't have push permission for some reason, but @joshdholtz can help out here

**Comment by joshdholtz** [comment]
@jorgifumi I can totally press buttons here! Thanks for the ping, @KrauseFx ❤️

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by joshdholtz** [comment]
@jorgifumi Quick question though! I’ve never used this but does break support for github? 🧐 it seems like we might need to do something like `(github || gitlab).pr_body` to provide support for both?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jorgifumi** [comment]
@joshdholtz I can't test it on GitHub now but hope it will not break GitHub support. If you look at my first commit, I switched from github.pr_body to gitlab.prbody and it worked for me, but I had the same worry about GitHub support so made my second commit with git.pr_body.
It worked fine on my GitLab and I assume that it will work with GitHub and maybe with others services (this is te reason of the title 😄 ) but I can't assure it.

**Comment by joshdholtz** [comment]
@jorgifumi Oh whoops! I was reviewing on mobile and I must have clicked into the wrong commit 🙈 Yeah yeah, we should be good with `git` 🚀 I will merge this for you then. Thanks for the contribution!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request merged**
